#!/bin/bash
docker run --rm -v $(pwd):/app -w /app titpetric/webshot-cli --window-size=2550/3300 --render-delay=200 title_page.html title_page.png
convert title_page.png title_page.jpg
rm title_page.png