test: test.cpp imagejpeg.cpp imagejpeg.h
	g++ test.cpp imagejpeg.cpp imagejpeg.h -ljpeg -o test
debug: test.cpp imagejpeg.cpp imagejpeg.h
	g++ test.cpp imagejpeg.cpp imagejpeg.h -ljpeg -g -Wall -D__DEBUG__ -o test
clean:
	rm test

